from django.urls import path
from .views import (
    customer_ledger_view,
    supplier_ledger_view,
    customer_udar_list,
    supplier_payable_list,
    customer_create,
    supplier_create,
    customer_debt_pdf,
    send_customer_reminder,
    supplier_record_pdf,
    send_supplier_record,
    add_customer_payment,
    add_supplier_payment,
    export_customer_ledger_pdf,
    export_supplier_ledger_pdf,
    expense_list_create,
    monthly_incoming_pdf,
    monthly_outgoing_pdf,
)

urlpatterns = [
    path("customer-ledger/<int:pk>/", customer_ledger_view, name="customer_ledger"),
    path("supplier-ledger/<int:pk>/", supplier_ledger_view, name="supplier_ledger"),
    path("customer-udar/", customer_udar_list, name="customer_udar"),
    path("supplier-payable/", supplier_payable_list, name="supplier_payable"),
    path("customers/new/", customer_create, name="customer_create"),
    path("suppliers/new/", supplier_create, name="supplier_create"),
    path("customer-udar/<int:pk>/debt.pdf", customer_debt_pdf, name="customer_debt_pdf"),
    path("customer-udar/<int:pk>/send-reminder/", send_customer_reminder, name="send_customer_reminder"),
    path("supplier-payable/<int:pk>/record.pdf", supplier_record_pdf, name="supplier_record_pdf"),
    path("supplier-payable/<int:pk>/send-record/", send_supplier_record, name="send_supplier_record"),
    path("customer-ledger/<int:pk>/add-payment/", add_customer_payment, name="add_customer_payment"),
    path("supplier-ledger/<int:pk>/add-payment/", add_supplier_payment, name="add_supplier_payment"),
    path("reports/customer-ledger.pdf", export_customer_ledger_pdf, name="export_customer_ledger_pdf"),
    path("reports/supplier-ledger.pdf", export_supplier_ledger_pdf, name="export_supplier_ledger_pdf"),
    path("expenses/", expense_list_create, name="expense_page"),
    path("reports/cashflow/incoming.pdf", monthly_incoming_pdf, name="monthly_incoming_pdf"),
    path("reports/cashflow/outgoing.pdf", monthly_outgoing_pdf, name="monthly_outgoing_pdf"),
]
