# Generated by Django 6.0.2 on 2026-02-21 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounttransaction_expense_customerpayment_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_customer_payments', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_supplier_payments', to='accounts.supplier'),
        ),
    ]
