# Generated by Django 6.0.2 on 2026-02-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url_name', models.CharField(blank=True, help_text='Django URL name, e.g. partner', max_length=120)),
                ('custom_url', models.CharField(blank=True, help_text='Optional direct URL path, e.g. /flights/', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sidebar Menu Item',
                'verbose_name_plural': 'Sidebar Menu Items',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
