# Generated by Django 6.0.2 on 2026-02-23 17:00

from django.db import migrations, models


def seed_public_page_content(apps, schema_editor):
    PublicPageContent = apps.get_model("public_booking", "PublicPageContent")
    rows = [
        (
            "about",
            "About Us",
            "We are a trusted travel organization focused on flights, visa support, Umrah packages, and holiday planning.",
        ),
        (
            "visa",
            "Visa Services",
            "Professional visa guidance and document support. Update this content from Django admin.",
        ),
        (
            "umrah",
            "Umrah Packages",
            "Affordable and premium Umrah packages. Update package details from Django admin.",
        ),
        (
            "holiday",
            "Holiday Packages",
            "Curated local and international holiday options. Update package details from Django admin.",
        ),
    ]
    for page_key, title, content in rows:
        PublicPageContent.objects.update_or_create(
            page_key=page_key,
            defaults={
                "title": title,
                "content": content,
                "is_active": True,
            },
        )


def unseed_public_page_content(apps, schema_editor):
    PublicPageContent = apps.get_model("public_booking", "PublicPageContent")
    PublicPageContent.objects.filter(page_key__in=["about", "visa", "umrah", "holiday"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("public_booking", "0002_sidebarmenuitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicPageContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "page_key",
                    models.CharField(
                        choices=[
                            ("about", "About Us"),
                            ("visa", "Visa Services"),
                            ("umrah", "Umrah Packages"),
                            ("holiday", "Holiday Packages"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Public Page Content",
                "verbose_name_plural": "Public Page Content",
                "ordering": ["page_key"],
            },
        ),
        migrations.RunPython(seed_public_page_content, unseed_public_page_content),
    ]
