# Generated by Django 6.0.2 on 2026-02-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('accountant', 'Accountant'), ('staff', 'Staff'), ('operations', 'Operations')], default='staff', max_length=20),
        ),
    ]
