# Generated by Django 6.0.2 on 2026-02-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cnic_passport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('check', 'Check'), ('online', 'Online'), ('system', 'System Auto')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplierledger',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('check', 'Check'), ('online', 'Online'), ('system', 'System Auto')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierledger',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
