# Generated by Django 6.0.2 on 2026-02-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('check', 'Check'), ('online', 'Online'), ('credit', 'Credit/Udar')], default='credit', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='travel_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='travel_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
