# Generated by Django 6.0.2 on 2026-02-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_payment_mode_ticket_ticket_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='source_channel',
            field=models.CharField(choices=[('erp', 'ERP'), ('public', 'Public Website')], default='erp', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='supplier_payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
    ]
